definitions:
  model.User:
    properties:
      accessKey:
        type: string
      account:
        type: string
      avatar:
        type: string
      balance:
        type: integer
      email:
        type: string
      gender:
        type: integer
      id:
        type: integer
      invitationCode:
        type: string
      phone:
        type: string
      profile:
        type: string
      role:
        type: string
      secretKey:
        type: string
      username:
        type: string
    type: object
  request.Email:
    properties:
      code:
        type: string
      email:
        type: string
    type: object
  request.UserLoginAccount:
    properties:
      account:
        type: string
      password:
        type: string
    type: object
  request.UserLoginEmail:
    properties:
      code:
        type: string
      email:
        type: string
    type: object
  request.UserRegisterAccount:
    properties:
      account:
        type: string
      checkPassword:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  request.UserRegisterEmail:
    properties:
      code:
        type: string
      email:
        type: string
      username:
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  response.UserLoginResponse:
    properties:
      expiresAt:
        type: integer
      token:
        type: string
      user:
        $ref: '#/definitions/model.User'
    type: object
info:
  contact: {}
  description: api接口文档
  title: Ax-API 接口文档
  version: "1.0"
paths:
  /api/email/send:
    post:
      consumes:
      - application/json
      parameters:
      - description: 邮箱
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Email'
      produces:
      - application/json
      responses:
        "200":
          description: 返回信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 获取验证码
      tags:
      - email
  /api/user/get:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 返回用户信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取用户信息
      tags:
      - user
  /api/user/login/account:
    post:
      consumes:
      - application/json
      parameters:
      - description: 账号,密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UserLoginAccount'
      produces:
      - application/json
      responses:
        "200":
          description: 返回用户信息,token,过期时间
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UserLoginResponse'
                msg:
                  type: string
              type: object
      summary: 用户根据账号登录
      tags:
      - user
  /api/user/login/email:
    post:
      consumes:
      - application/json
      parameters:
      - description: 邮箱,验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UserLoginEmail'
      produces:
      - application/json
      responses:
        "200":
          description: 返回用户信息,token,过期时间
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UserLoginResponse'
                msg:
                  type: string
              type: object
      summary: 用户根据邮箱登录
      tags:
      - user
  /api/user/register/account:
    post:
      consumes:
      - application/json
      parameters:
      - description: 账号,密码,确认密码,用户名
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UserRegisterAccount'
      produces:
      - application/json
      responses:
        "200":
          description: 返回注册信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 用户根据账号注册
      tags:
      - user
  /api/user/register/email:
    post:
      consumes:
      - application/json
      parameters:
      - description: 邮箱,验证码,用户名
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UserRegisterEmail'
      produces:
      - application/json
      responses:
        "200":
          description: 返回注册信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 用户根据邮箱注册
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: a-token
    type: apiKey
swagger: "2.0"
